/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory;

import java.awt.BorderLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author user
 */
public class allexpenses extends javax.swing.JDialog
{
static String url = "jdbc:mysql://localhost:3306/inventory";
    static String username = "root";
    static String password = "this";
    SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
String first="2000-01-01";
String last="2020-01-01";
    JTable table;
TableModel model;
String [][] data=null;
String name;
    String description;
    String amt;
    String date;

    /**
     * Creates new form allexpenses
     */
    public allexpenses() {
        initComponents();
        //data=this.getData();
        table();
        update();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
       
        this.setTitle("ALL EXPENSES");
        try {
           Class.forName("com.mysql.jdbc.Driver");
             Connection conn = DriverManager.getConnection(url, username, password);
            String sql = "SELECT name FROM listexpense";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet resultSet = stmt.executeQuery();
            while (resultSet.next()) {
               jComboBox1.addItem(resultSet.getString(1));
             }
            conn.close();
        } catch (Exception exc) {  // process error
            System.out.println("process error" + exc);
            }
    }
    public void fill(String namef,String descriptionf,String amtf,String datef){
name=namef;
description=descriptionf;
amt=amtf;
jComboBox1.setSelectedItem(namef);
//nam.setText(name);
date=datef;
des.setText(descriptionf);
amount.setText(amtf);
Date ee=Date.valueOf(datef);
        jDateChooser3.setDate(ee);

}
 public void table(){
        
   /// table.removeAll();
    String[] headers={ "NAME","DESCRIPTION","DATE","AMOUNT"};

//data[i][j]=i*j;

// make table model with this data..
DefaultTableModel model = new DefaultTableModel(data, headers);
model.fireTableDataChanged();
table = new JTable(model);
//table.setCellSelectionEnabled(true);
//table.setEditingRow(0);
JScrollPane scrollPane = new JScrollPane(table);
//table.setFillsViewportHeight(true);
jPanel2.add(scrollPane,BorderLayout.CENTER);
scrollPane.setBounds(0,0,450, 470);
table.addMouseListener(new MouseAdapter() {
public void mouseClicked(MouseEvent e) {
    getData();
int row = table.getSelectedRow();
System.out.println(data[0][0]);
int col = table.getSelectedColumn();
String name=data[row][0];
String des=data[row][1];
String date=data[row][2];
String amt=data[row][3];


//editexpense2 b=new editexpense2(null,true);
fill(name, des, amt, date);
//b.setVisible(true);
System.out.println("row is "+row+" and " +col);
}
});    
    
    }
     public String [][] getData(){
    
     
    String [][] sample=null;
String str="SELECT * from expenses where date<'"+last+"'&& date>'"+first+"'";

		  Connection cn;
		  ResultSet rs;
		  Statement st;

		  try {
		   // Change the database name, hosty name,
		   // port and password as per MySQL installed in your PC.
		   cn=DriverManager.getConnection("jdbc:mysql://" +
		     "localhost:3306/inventory","root","this");
		   st=cn.createStatement();

		   rs=st.executeQuery(str);
                   
                 
if(rs.next()){
rs.last();

sample=new String [rs.getRow()][4];
rs.beforeFirst();
}
int rowcount=0;

		   while(rs.next())
		   {
		    
sample[rowcount][0]=rs.getString(1);
sample[rowcount][1]=rs.getString(4);
sample[rowcount][2]=rs.getString(3);
sample[rowcount][3]=rs.getString(2);



		    
//System.out.println(sample[1][1]);		    
                   
                  
rowcount++;
                    
		   }
                  rs.close();
                  cn.close();

		  } catch (SQLException e) {

		   e.printStackTrace();
		  }
                  data=sample;
                  return sample;
		 }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        des = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(450, 470));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jLabel1.setText("START DATE:");

        jLabel2.setText("STOP DATE");

        jButton1.setText("FILTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("EDIT");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        jLabel3.setText("NAME:");

        jLabel4.setText("DESCRIPTION:");

        des.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("DATE:");

        jLabel6.setText("AMOUNT");

        amount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(40, 40, 40)
                        .addComponent(jButton3))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(amount, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(des, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jDateChooser3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
filter();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        insert();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 int y;        // TODO add your handling code here:
        y = JOptionPane.showConfirmDialog(null, "Do you want to delete?", "Confirm", JOptionPane.YES_NO_OPTION);

        if (y == 0) {        delete();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
        else{}}
    /**
     * @param args the command line arguments
     */
    public void filter(){
        String dateTopay="";
        String select="";
    try{
        Calendar currentDate = Calendar.getInstance();
        
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
     
//      sad.format(ove);
        java.util.Date aa=jDateChooser1.getDate();
        java.util.Date bb=jDateChooser2.getDate();
        
            select= formatter.format(bb.getTime());
            dateTopay= formatter.format(aa.getTime());
        }catch(Exception ex){
        
        
        
        }
    
     if(dateTopay.equals("")){
    JOptionPane.showMessageDialog(jPanel1, "Sorry, Date", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        else if(select.equals("")){
    
     JOptionPane.showMessageDialog(jPanel1, "Sorry, Date", "Error!", JOptionPane.ERROR_MESSAGE);
    //exp.requestFocus();
    }
        else{
        
        first=dateTopay;
                last=select;
                getData();
        update();}
    }
    public void delete(){
        
   try {
           Class.forName("com.mysql.jdbc.Driver").newInstance();
             Connection conn = DriverManager.getConnection(url, username, password);
            String sql = ("delete from expenses where name='"+name+"' && date='"+date+"' && description='"+description+"'");
            
            PreparedStatement stmt = conn.prepareStatement(sql);
            
            
            
            int u=stmt.executeUpdate();
    if(u>0){
    JOptionPane.showMessageDialog(jPanel1, "DELETED!", "Success!", JOptionPane.INFORMATION_MESSAGE);
    update();
    //this.dispose();
    
    
    }
    else{
    
    JOptionPane.showMessageDialog(jPanel1, "Not done!", "ERROR!", JOptionPane.ERROR_MESSAGE);
    
    
    }
    
   }
   catch(Exception ex){}
    
    }
    public void insert(){
        String select="";
        String  dateTopay="";
        try{
      select=(String)jComboBox1.getSelectedItem();
        }catch(Exception ex){
        
        jComboBox1.requestFocus();
        }
        try{
        Calendar currentDate = Calendar.getInstance();
        
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
     
//      sad.format(ove);
        java.util.Date aa=jDateChooser3.getDate();
        
             
            dateTopay= formatter.format(aa.getTime());
        }catch(Exception ex){
        
        jDateChooser3.requestFocus();
        
        }
          
        try{
double tamt=Double.parseDouble(amount.getText());


}
catch(NumberFormatException ex){

amount.setText("");


}
        if(dateTopay.equals("")){
    JOptionPane.showMessageDialog(jPanel1, "Sorry, Select Date", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        else if(select.equals("")){
    
     JOptionPane.showMessageDialog(jPanel1, "Sorry, Select Expense", "Error!", JOptionPane.ERROR_MESSAGE);
    
    }
    else if(amount.getText().equals("")){
    
     JOptionPane.showMessageDialog(jPanel1, "Sorry, ENTER AMOUNT", "Error!", JOptionPane.ERROR_MESSAGE);
    amount.requestFocus();
    }
    else if(des.getText().equals("")){
    
     JOptionPane.showMessageDialog(jPanel1, "Sorry, ENTER DESCRIPTION", "Error!", JOptionPane.ERROR_MESSAGE);
    des.requestFocus();
    }
    
        else{
    delete2();
    try {
           Class.forName("com.mysql.jdbc.Driver").newInstance();
             Connection conn = DriverManager.getConnection(url, username, password);
            String sql = ("INSERT INTO expenses values(?,?,?,?)");
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1,(String)jComboBox1.getSelectedItem());
            stmt.setString(2,amount.getText());
             stmt.setString(3,dateTopay);
            stmt.setString(4,des.getText());
            
            
            int u=stmt.executeUpdate();
            if(u>0){
            
            JOptionPane.showMessageDialog(jPanel1, "Saved!", "Success!", JOptionPane.INFORMATION_MESSAGE);
            update();
            }
    }catch(Exception ex){
    
        
    ex.printStackTrace();;
    
    }
    
    } 
    }
    public void delete2(){
    try {
           Class.forName("com.mysql.jdbc.Driver").newInstance();
             Connection conn = DriverManager.getConnection(url, username, password);
            String sql = ("delete from expenses where name='"+name+"' && date='"+date+"' && description='"+description+"'");
            
            PreparedStatement stmt = conn.prepareStatement(sql);
            
            
            
            int u=stmt.executeUpdate();
            if(u<0){
                JOptionPane.showMessageDialog(jPanel1, "Not done try again!", "ERROR!", JOptionPane.ERROR_MESSAGE);
this.dispose();
            
            }
       }
    catch(Exception ex){
    
    
    }
    
    
    
    
    }
    public void update(){
    
    String str="SELECT name as 'NAME', description as 'DESCRIPTION',date as 'DATE',amt as 'amt' from expenses where date<='"+last+"'&& date>='"+first+"'";

		  Connection cn;
		  ResultSet rs;
		  Statement st;

		  try {
		   // Change the database name, hosty name,
		   // port and password as per MySQL installed in your PC.
		   cn=DriverManager.getConnection("jdbc:mysql://" +
		     "localhost:3306/inventory","root","this");
		   st=cn.createStatement();

		   rs=st.executeQuery(str);
                   table.setModel(DbUtils.resultSetToTableModel(rs));
                  }catch(Exception ex){ex.printStackTrace();}
    
    
    }
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(allexpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(allexpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(allexpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(allexpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new allexpenses().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JTextField des;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
