/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class login extends javax.swing.JDialog {
    static String nam,pas,fro,h,ww;
    int userlevel;
    DBConnection db= new DBConnection();
    static PreparedStatement stmt;
    static ResultSet resultSet;

    
    /**
     * Creates new form login
     */
    public login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
       
        this.setTitle("Login");
        this.addWindowListener(new java.awt.event.WindowAdapter() {

            @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        int y=0;
y=JOptionPane.showConfirmDialog(jPanel1,"Do Really You Want to Exit This Application?","Confirm!",JOptionPane.YES_NO_OPTION);
if(y==0)
{
System.exit(0);
 }
 else if(y==1){
     dispose();
   login n=new login (new javax.swing.JFrame(), true); 
   
 n.setVisible(true);  
 }    }
                });
         try {
             
            String sql = "SELECT user FROM login";
            stmt = db.prepareStatement(sql);
            resultSet = stmt.executeQuery();
            //resultSet=db.resultSet();
            while (resultSet.next()) {
               name.addItem(resultSet.getString(1));
             }
            
        } catch (Exception exc) {  // process error
            System.out.println("process error" + exc);
                 ;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PLEASE LOGIN......");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory/Login-toolbar-64.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, Short.MAX_VALUE)
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4))
        );

        jButton1.setText("QUIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("USERNAME");

        jLabel3.setText("PASSWORD:");

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(60, 60, 60)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(name, 0, 218, Short.MAX_VALUE)
                    .addComponent(jPasswordField1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int y=0;
y=JOptionPane.showConfirmDialog(null,"Do Really You Want to Exit This Application?","Confirm!",JOptionPane.YES_NO_OPTION);
if(y==0)
{
System.exit(0);
 }
 else if(y==1){
     
 }           // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Date  current=new Date();
        String expire=null;
        String exp="";
        int count=0;
        
    try {
        
           expire=new SimpleDateFormat("yyyyMMdd").format(current);
            String msql = "SELECT expiryDate FROM dates WHERE expiryDate<'"+expire+"'";
            stmt = db.prepareStatement(msql);
            resultSet  = stmt.executeQuery();
             
             while(resultSet.next()){
                 count=1;            
             }  
             
    } catch (SQLException ex) {
        Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
    }
     
        nam=(String)name.getSelectedItem();
        String sd="SELECT USER";
        if(jPasswordField1.getText().equals("")){
                         JOptionPane.showMessageDialog(jPanel1,"Sorry, You Did Not Enter Any Password","Warning!",JOptionPane.WARNING_MESSAGE);
}
        else if(nam.equals(sd)){
        JOptionPane.showMessageDialog(jPanel1,"Sorry, Please select user","Warning!",JOptionPane.WARNING_MESSAGE);
        }else if(count>0){
            JOptionPane.showMessageDialog(jPanel1,"Database connection error.... Contact the administrator !!!!!","Error!",JOptionPane.ERROR_MESSAGE);
        }
else {
        
        pas=jPasswordField1.getText();
        int i=0;
              try {
           
            String sql = "SELECT userlevel FROM login WHERE user='"+nam+"'";
             stmt = db.prepareStatement(sql);
             resultSet = stmt.executeQuery();
            while (resultSet.next()) {
                i=1;
               ww=resultSet.getString(1);
              }
            
        } catch (Exception exc) {  // process error
            exc.printStackTrace();
            System.out.println("process error" + exc);
        }  
         if(i==1)
               {
                  // comfree();
                   //free();
                // level();
                 //  usern();

                  // comp();
                   free();
                   usern();
                   this.dispose();
                   
                home m=new home(new javax.swing.JFrame(), true);
                    m.setVisible(true);

               }
         else
               {
                  JOptionPane.showMessageDialog(jPanel1," The Username Does Not Match With\n The Password You Entered!","Error!",JOptionPane.WARNING_MESSAGE);
                   jPasswordField1.setText("");
               }

}   
           // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
nam=(String)name.getSelectedItem();
        String sd="SELECT USER";
        if(jPasswordField1.getText().equals("")){
                         JOptionPane.showMessageDialog(jPanel1,"Sorry, You Did Not Enter Any Password","Warning!",JOptionPane.WARNING_MESSAGE);
}
        else if(nam.equals(sd)){
        JOptionPane.showMessageDialog(jPanel1,"Sorry, Please select user","Warning!",JOptionPane.WARNING_MESSAGE);
        }
else {
        
        pas=jPasswordField1.getText();
        int i=0;
              try {
          
            String sql = "SELECT userlevel FROM login WHERE user='"+nam+"'";
             stmt = db.prepareStatement(sql);
             resultSet = stmt.executeQuery();
            while (resultSet.next()) {
                i=1;
               ww=resultSet.getString(1);
              }
            
        } catch (Exception exc) {  // process error
            exc.printStackTrace();
            System.out.println("process error" + exc);
        }  
         if(i==1)
               {
                  // comfree();
                   //free();
                // level();
                 //  usern();

                  // comp();
                   free();
                   usern();
                   this.dispose();
                   
                home m=new home(new javax.swing.JFrame(), true);
                    m.setVisible(true);

               }
         else
               {
                  JOptionPane.showMessageDialog(jPanel1," The Username Does Not Match With\n The Password You Entered!","Error!",JOptionPane.WARNING_MESSAGE);
                   jPasswordField1.setText("");
               }

}   
          // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed
public void usern(){
String ss=(String) name.getSelectedItem();

//String aq=String.valueOf(userlevel);
try
             {
 stmt=  db.prepareStatement
("INSERT INTO holder values(?,?)");
stmt.setString(2,ww);
stmt.setString(1,ss);
System.out.println(ww+"hhhhh");
//psmnt.setString(1,fn.getText());
int s = stmt.executeUpdate();
stmt.close();
if(s>0){System.out.println("inserted");}
             }
   catch (Exception ex) {
       ex.printStackTrace();
System.out.println("Found some error : "+ex);
    JOptionPane.showMessageDialog(null,"Error "+ex+"","Error!",JOptionPane.ERROR_MESSAGE);

}}
public void free(){

try
             {


 stmt=db.prepareStatement
("Truncate table holder");

stmt.executeUpdate();
stmt.close();

             }
   catch (Exception ex) {
System.out.println("Found some error : "+ex);
    JOptionPane.showMessageDialog(null,"Error "+ex+"","Error!",JOptionPane.ERROR_MESSAGE);

}
} 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                login dialog = new login(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JComboBox name;
    // End of variables declaration//GEN-END:variables
}
